name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "berge.greg@gmail.com"
        git config --global user.name "Greg Bergé"

    - name: Install dependencies
      shell: bash
      run: pnpm install
